### ISSUE TITLE
ConcurrentModificationException since update to v4

### ISSUE THREAD

**Issue by juliahexen** [TagCommander/Android#3]
Hello,
we recently updated the TagCommander library from v3 to v4. Now we have some crashes in our apps we didn't have with v3:

> Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
       at com.tagcommander.lib.core.TCDynamicStore.addData(TCDynamicStore.java:37)
       at com.tagcommander.lib.TCPredefinedVariables.addData(TCPredefinedVariables.java:1110)
       at com.tagcommander.lib.TCPredefinedVariables.onReceive(TCPredefinedVariables.java:1434)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:308)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:118)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5631)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by CommandersAct** [comment]
Hello !
Thank you for reporting this issue.

I uploaded a new version of the "core" module better handling synchronisation of the TCDynamicStore.

core:4.1.4

Please tell me if it corrected the issue, it's pretty difficult to reproduce ConcurrentModification issues.

**Comment by juliahexen** [comment]
Thank you! :)
I will post an update when we have a new app released.

**Comment by guntherhoppe** [comment]
Hi there,
I tried the 4.1.4 core. The exception still happens. The TCDynamicStore#clearData also modify the maps but isn't synchronized.

```
java.util.ArrayList$Itr.next (ArrayList.java:831)
com.tagcommander.lib.core.TCDynamicStore.addData (TCDynamicStore.java:39)
com.tagcommander.lib.TCPredefinedVariables.addData (TCPredefinedVariables.java:1110)
com.tagcommander.lib.TCPredefinedVariables.onReceive (TCPredefinedVariables.java:1434)
android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts (LocalBroadcastManager.java:308)
...
```

**Comment by CommandersAct** [comment]
Hello !

I added protections around the clearData.
I'm a bit surprised of the log you sent last hit as this is not calling clearData. Since i'm using 2 lists in my addData I also separated the locks on each list to be sure there is not one list synchronised while another is modified.

You can update to core:4.1.5, it's available on bintray.

**Comment by guntherhoppe** [comment]
Mhh - ok. I looked at the code in more detail. The problem seems not to be the clearData. The problem probably is that you modify the orderedKeys while iterate over them.  
In addData you iterate over orderedKeys and call the addData with key-value pair, which adds a value to the orderedKeys if not contained, which leads to the ConcurrentModificationException. In principal like this:

```
    public void iteratorTest() {

        List<String> list = new ArrayList<>();
        list.add("One");
        list.add("Two");
        list.add("Three");

        for(String s : list) {
            if(!list.contains("Four")) {
                list.add("Four");
            }
        }

    }
```

**Comment by CommandersAct** [comment]
oh! Indeed this is a very bad thing. It's hidden because it's calling another function which is doing the add.

I'll correct that as soon as possible. Unfortunately this won't be before Monday.

**Comment by CommandersAct** [comment]
It's actually not the same store.

` public void addData(TCDynamicStore store)

    {
       if (store != null)
        {
            for (String key : store.orderedKeys)
            {
                addData(key, store.getData(key));
            }
        }
    }
`

`public void addData(String key, String value)

    {
        if (key != null && value != null)
        {
            if (!orderedKeys.contains(key))
            {
                    orderedKeys.add(key);
            }
                dynamicStore.put(key, value);
        }
    }`

So this is sadly not the issue :(

(I removed the synchronised for readability)

**Comment by guntherhoppe** [comment]
Mhh - ok, I see. Not sure what instance the supplied store actually is. But the problem remains that the ```orderKeys``` are changed anyway while iterating over them in the ```addData```. Because they are public this in principal can be everywhere else (haven't the complete source code). 

If you do not use an Iterator (Enumeration) but iterate directly over the ```orderedKeys``` values, you maybe can solve this problem as well.
```
    public void iteratorTest2() {

        List<String> list = new Vector<>();
        list.add("One");
        list.add("Two");
        list.add("Three");

        for(int i = 0; i < list.size(); i++) {
            if(!list.contains("Four")) {
                list.add("Four");
            }
        }

    }
```

One more thing: I think there should be a sync also for read access. For ```dynamicStore``` you use the ```Hashtable``` which is synchronized. Maybe you should use a ```Vector``` instead of an ```ArrayList``` for ```orderedKeys``` too.

**Comment by CommandersAct** [comment]
I tried 2 things, I searched all possible accesses without finding anything suspicious, so I synchronised the gets, but if my guess is correct, the issue is in the implementation of "contains". So I changed the way I was synchronising around the contains.

As it's a bit complicated to test, do you have a build that can reproduce the issue or do you only have it in production? Would it be better for me to give you tests releases in jar/aar form with a link to download them, or is it better to push them to Bintray hoping it's the last time?

Thank you for you help !

**Comment by guntherhoppe** [comment]
Mhh, I know - I'm also not able to reproduce this error in my dev/test environment. It happens only within our store version. :/ Would be great if you can deploy a new version of TC core on Bintray.

Thanks for your support!

**Comment by CommandersAct** [comment]
Uploaded them on Bintray, create a new version for the SDK since I tried to synchronise the addition to the predefined variables' store.

SDK:4.1.3
core:4.1.5

Re-uploaded the core, but kept the version for now. You will probably need to remove the cached version or core to force the re-upload.

Something like this: https://stackoverflow.com/questions/13565082/how-can-i-force-gradle-to-redownload-dependencies

I'd rather not create 10 versions if it doesn't correct the crash. Next time I'll try to find a way to create "beta" versions which might be more convenient for those cases.

Thank you for your help !

**Comment by guntherhoppe** [comment]
Ok - perfect. I currently schedule a new release of our app which should also include your fix/update. Many thanks! - perfect timing :)

**Comment by guntherhoppe** [comment]
We started Play Store introduction of our new release. I'll let you known if the issue is solved.

**Comment by guntherhoppe** [comment]
Mhh - unfortunately the exception still happens, the problem still exists with versions SDK 4.1.3, core: 4.1.5 :(

```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:831)
       at com.tagcommander.lib.core.TCDynamicStore.addData(TCDynamicStore.java:43)
       at com.tagcommander.lib.TCPredefinedVariables.addData(TCPredefinedVariables.java:1112)
       at com.tagcommander.lib.TCPredefinedVariables.onReceive(TCPredefinedVariables.java:1446)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:308)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:118)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

Maybe you can simply change the loop in a next version from:
```
for (String key : store.orderedKeys) {
...
}
```
to 
```
int orderedKeySize = orderedKeys.size();
for (int i = 0; i < orderedKeySize; i++) {
...
}
```
as I mentioned above. This of course does not solve the underlying problem. But so we can prevent the crashes for our users for now . Afterwards you could take more time to analyse the issues real origin.

**Comment by CommandersAct** [comment]
Done. 
I also tried to synchronised TCPredefinedVariables.addData.
I saw that some calls where made directly to the store and not going through this addData, so I corrected this as well.

The versions are still the same, you will need to clean the cache again. Sorry about that.

Thank you again for your help!

**Comment by guntherhoppe** [comment]
Hi,
with the newest version I have a different problem now. Can it be that you have removed the ```getDynamicStore``` method in class ```com.tagcommander.lib.TagCommander```? TC is integrated in our app through another internal library, which I unfortunately cannot change. This library uses the ```getDynamicStore``` method. I'm only able to exclude the TC libs of this lib while gradle import, in favor of using the latest TC libs directly. But this requires a non-changed interface. :( 
Maybe the problem is occurred through the access here, because the ```TCDynamicStore``` is get from ```TagCommander``` class to add some data. 

Is this interface change strictly required for you? I'm afraid yes, or? (Means that it will take more time until I can release a new version)

**Comment by CommandersAct** [comment]
I thought I'd remove all accesses to the dynamic stores that are not done by the SDK directly so to prevent possible bypass of synchronised.

If you can't do without this, I'll make you another version putting it back. Is there only the one from TagCommander that is needed?

edit: It's online

**Comment by guntherhoppe** [comment]
Yes, it is the only one. Thanks. :)
But can it still be ensured that the problem no longer occurs?

**Comment by CommandersAct** [comment]
I'll keep the function there.

It's a bit too bad since it really does open a door to put stuff in the dynamic store without any controls and it was actually created simply to allow my unit tests to access and check the inside of the store :)

But if you need it, so be it. If you have a way to change the other library at some point, please tell me.

**Comment by guntherhoppe** [comment]
Perfect.
Set it to deprecated. I will pass it on internally. 
Many thanks.

**Comment by guntherhoppe** [comment]
Hi there.
Sorry for the late answer. Finally I could upload a patched version of our app to the Play Store. The exception now doesn't occur any more. 👍 

Thanks + happy xmas!

**Comment by CommandersAct** [comment]
Happy to hear that! Merry xmas!
