### ISSUE TITLE
pom.xml does not include dependencies 

### ISSUE THREAD

**Issue by SebastienChauvin** [TagCommander/Android#8]
We have noticed that the README for each module lists all dependencies required by the library. It is good practice to have the pom.xml describe all dependencies so that developers do not have to manually copy and paste dependencies.

Currently the pom.xml hosted on JCenter does not include any dependency

https://dl.bintray.com/tagcommander/maven/com/tagcommander/lib/SDK/4.3.0/SDK-4.3.0.pom

**Comment by CommandersAct** [comment]
Hello !
Thank you, I will check this when I'll have some time.

**Comment by pietrini** [comment]
Any updates on this issue ?

**Comment by CommandersAct** [comment]
Not yet I'm sorry I have many other priorities at the moment :(
A bug has been filed and it will be treated when the sprint permits it.

**Comment by pietrini** [comment]
Any updates on this issue ?

**Comment by CommandersAct** [comment]
We actually removed them because putting our dependencies were causing issues to some clients using dependencies that were too old. (Can't find any traces lefts about that request though)

**Comment by pietrini** [comment]
That's the exact reason of why you should declare your dependencies. If you have some clients who use old ones version of them, they will have a warning of a potential issue with TC lib working as expected. And for the other ones, a complete declaration about what you're using for the build system.

BTW clients with dependencies issues could/should use the gradle exclude group declaration with TC lib import.

It's more secure for you to declare a complete set of your dependencies instead of removing them because of some clients dependencies issues.

**Comment by CommandersAct** [comment]
Should be better now.
